chore: datafabrikken veiviser helmchart
datadeling/helm-chart pull request #2
Opened 2022-05-18 07:40 UTC by jeffreiffers

Fixes #1

2022-05-18 07:58 UTC, stigbd approved these changes

2022-05-18 11:08 UTC, NilsOveTen requested changes

2022-05-18 11:08 UTC, NilsOveTen commented on .idea/.gitignore
> +# Default ignored files
fjern disse filene og legg til .idea i gitignore

2022-05-18 12:12 UTC, NilsOveTen approved these changes
Har ikke 100% kontroll på yaml-syntax, ok om det er part-greiene er uten tab ellers

2022-05-18 12:12 UTC, NilsOveTen commented on helm-chart-sources/datafabrikken-veiviser-dele-data/templates/deployment.yaml
> +        - containerPort: 8080
Tror kanskje det feiler uten tab her
```suggestion
          - containerPort: 8080
```

2022-05-19 08:28 UTC, jeffreiffers commented on .idea/.gitignore
> +# Default ignored files
Det er gjort slik mange andre steder så tror det går fint.

2022-05-19 08:28 UTC, jeffreiffers commented on helm-chart-sources/datafabrikken-veiviser-dele-data/templates/deployment.yaml
> +        - containerPort: 8080
Det er gjort slik mange andre steder så tror det går fint.

2022-05-19 08:35 UTC, merged